//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCHut_API.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Invoice
    {
        [Key]
        public int Invoice_id { get; set; }
        public int Customer_id { get; set; }
        public System.DateTime Date { get; set; }
        public int Branch_manager_id { get; set; }
        public double Added_sub_total { get; set; }
        public int Discount_id { get; set; }
        public double Total_amount { get; set; }
        public int Branch_id { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Branch_Manager Branch_Manager { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Discount Discount { get; set; }
    }
}
