//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCHut_API.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Sales_Record
    {
        [Key]
        public int Sales_id { get; set; }
        public int Customer_id { get; set; }
        public System.DateTime Date { get; set; }
        public int Product_id { get; set; }
        public double Price { get; set; }
        public int Quantity { get; set; }
        public double Sub_total { get; set; }
        public int Delivery_status { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
    }
}
